credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "Credentials for git"
          id: "49d83168-1c74-46d9-92ba-1ef342c81638"
          password: "{AQAAABAAAAAQs63G2g3KpEGl3JRC0yowH2WR0jWl4bsgfKy25fC10Mc=}"
          scope: SYSTEM
          username: "git@git.com"
      - usernamePassword:
          id: "sinajmon"
          password: "Sinajgit@75"
          scope: GLOBAL
          username: "sinaj75@gmail.com"
      - aws:
          accessKey: "AKIATSMVQX4KXUYQGMWR"
          description: "aws-jenkins-demo"
          id: "aws-jenkins-demo"
          scope: GLOBAL
          secretKey: "YmeLaBp92Vc2VK51C/oY6cpMk+IboLNZSAigB3ep"
      - gitHubApp:
          appID: "370126"
          description: "DevopsOrganise"
          id: "DevopsOrganise"
          privateKey: "-----BEGIN PRIVATE KEY-----
          
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+FkYBtiwRNjJg
/ldVDmmciUGR9l+2f8A+DhPQaJRf/l/UNgx8ZC5jJLkt7NTmTNSA9L4D2B5Kqdjv
Inf6anpsZQTzWkToBv7TkFuEcgF7WeZn4PMx1GHfGvOiRI28xyJPUEM1Ldy3ZAAp
oqLSCN3kh7BgNq05nWhcNNOBR/ElE7yHU6D74JQuSqdvlXtZO6selv8eD1X5iXxk
Ny1p7+awvGPb8rzXmHhOsBI8qtCG80RgdH3ibaF2+6gCcFPDKxHW8b6fOIXj8LEb
9l0tNFm6ZBKlVJZC1/RoxXIy1wJAXUmKhC9qZc7J80pLLc158k31Jy0M2aM3Bdf4
BShHAC/FAgMBAAECggEALO/NCviLAGKklENsV+I5W1UjWCM7S0R2KPVg/8LJWMwk
0WEZoIp6YNu8nzu+tNby4a16AiSkPJhcfWPTozJq0JctDW6InaWRtmgJCo19BjEh
g+ss8tm3bWvMrs6wBzG4TbG2waqe5AfS9gTJowePlUfyjTw/xUAN/MZMPeLJAi94
8Rh5eQYIrup+zsaoLKNCNA9UQDUDfJwrvMoq2aAajyARQ0qnfE5DsbKOCr/S8wLP
+WE33IhOicwlO//8scRP/XuLayNLpko68A2IKqK1DiKEBo7+Gsz1tVcXUfFkcUKA
JX1krraRozJSsy1Ee/q/v8E9nZxKfUyeY+gIbHCSnQKBgQDgK6goiuE6EBbY4x7A
Xj0vye1OKoCslQCJuD7WWRQG6VONGjwcoOzL0SX7B+bsJrKh5q80VmMylT0PfV9x
2zP7DbHO9e1fm/3nX49cWdCGyehUjhJlhITSVxiGAQ3Frc5vn5I+HpUFPJgXVUkG
X9tDUpsRv0Q/+O5LW0AhQDzG0wKBgQDZE7geP1Xww67lR9mkNMDeL6QmkvCAwDri
fu2nwQSE5Tlo5uSQql93jKeGAh9jYQh0Z5upDrkaVDEvtU+pHlxZfskd3dOniRHh
tP31iZCKu+EctCZWUk8XyVJttLDTLJu/3Daxwt0oXlBxpIxug83YtXeLkRm5NH1w
WS5gXJZABwKBgEenLLToz10Tz3m7/xRWCxC/Zo7Znw+LAQUEU3GIP5KF+iLcA+LS
vV3YmF9JA1Lwe6Csb8w24LZGZaIR3PQzsMXKds9EZH9vCRVvwg8u1ix/VTfRwaeZ
WCszk68hnxlUmOutAb3BYLivyZ2LsS/Ma/V07gQaMuKP2vtTS4hVVBfpAoGBAL26
PnIxaSvF3FcJNXAPq4KGoTIVu57MZKsRxSWZzhlZP5QwOhU207npdYHq2QRDCuCy
rZpVA/O/Ij5Qeg+WOaD+70jrWNJVOwvK5Sx1z59yFo6/5cIMrpRboW/BPctUccx+
7E7xwdpGlIi/CP6OtJtz/8g8Sf9VoU1QpPgT9D6BAoGBAM84qIOAr/LLpBilkm/m
wnNc/XCLnzAz4T0aWgZ6QVrVduZOR6V0CQiXgGmL757Fhl1+vjwYp0u90tZyplpt
rNczE8Bs9yCR2z171Ow6QcVJd4Fs4w6/IXHdH1yMEFhM97anw2GhbU/1L6EU927t
6z1SYEvPtWnbxw7L1ZHsqOn2

-----END PRIVATE KEY-----"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "hudson.util.DoubleLaunchChecker"
  labelAtoms:
  - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  nodeMonitors:
  - diskSpaceMonitor:
      freeSpaceThreshold: "1GB"
  - tmpSpace:
      freeSpaceThreshold: "1GB"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 3
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        properties:
        - "apiToken"
        - "mailer"
        - "favorite"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - "experimentalFlags"
  slaveAgentPort: 50000
  systemMessage: "Jenkins configured automatically by Jenkins\r\n\r\n"
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
jobs:
  - script: >
      multibranchPipelineJob('configuration-as-code') {
          branchSources {
              git {
                  id = 'configuration-as-code'
                  remote('https://github.com/sinajmon/develop.git')
              }
          }
      } 
  - url: https://raw.githubusercontent.com/sinajmon/seedpipe/main/seed.groovy    
  - url: https://raw.githubusercontent.com/sinajmon/seedorganization/main/seed.groovy
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  prism:
    theme: PRISM
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  copyartifact:
    mode: PRODUCTION
  envInject:
    enableLoadingFromMaster: false
    enablePermissions: false
    hideInjectedVars: false
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: -1
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        manageHooks: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
    endpoints:
    - apiUri: "https://api.github.com"
      name: "github"
  gitHubPluginConfig:
    configs:
    - manageHooks: false
      name: "github"
    hookUrl: "http://ec2-52-201-237-45.compute-1.amazonaws.com:8080/github-webhook/"
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    injectCcudExtension: false
    injectMavenExtension: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://ec2-52-201-237-45.compute-1.amazonaws.com:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pluginImpl:
    enableCredentialsFromNode: false
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  upstream:
    globalUpstreamFilterStrategy: UseOldest
  warningsParsers:
    consoleLogScanningPermitted: false
tool:
  dotNetConfiguration:
    buildAllowed: true
    cleanAllowed: true
    listPackageAllowed: true
    nuGetDeleteAllowed: true
    nuGetLocalsAllowed: true
    nuGetPushAllowed: true
    packAllowed: true
    publishAllowed: true
    restoreAllowed: true
    telemetryOptOut: true
    testAllowed: true
    toolRestoreAllowed: true
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
